// @generated by protoc-gen-connect-web v0.3.2 with parameter "target=ts"
// @generated from file flow/access/access.proto (package flow.access, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AccountResponse, BlockHeaderResponse, BlockResponse, CollectionResponse, EventsResponse, ExecuteScriptAtBlockHeightRequest, ExecuteScriptAtBlockIDRequest, ExecuteScriptAtLatestBlockRequest, ExecuteScriptResponse, ExecutionResultForBlockIDResponse, GetAccountAtBlockHeightRequest, GetAccountAtLatestBlockRequest, GetAccountRequest, GetAccountResponse, GetBlockByHeightRequest, GetBlockByIDRequest, GetBlockHeaderByHeightRequest, GetBlockHeaderByIDRequest, GetCollectionByIDRequest, GetEventsForBlockIDsRequest, GetEventsForHeightRangeRequest, GetExecutionResultForBlockIDRequest, GetLatestBlockHeaderRequest, GetLatestBlockRequest, GetLatestProtocolStateSnapshotRequest, GetNetworkParametersRequest, GetNetworkParametersResponse, GetTransactionByIndexRequest, GetTransactionRequest, GetTransactionsByBlockIDRequest, PingRequest, PingResponse, ProtocolStateSnapshotResponse, SendTransactionRequest, SendTransactionResponse, TransactionResponse, TransactionResultResponse, TransactionResultsResponse, TransactionsResponse } from "./access_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * AccessAPI is the public-facing API provided by access nodes.
 *
 * @generated from service flow.access.AccessAPI
 */
export const AccessAPI = {
  typeName: "flow.access.AccessAPI",
  methods: {
    /**
     * Ping is used to check if the access node is alive and healthy.
     *
     * @generated from rpc flow.access.AccessAPI.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLatestBlockHeader gets the latest sealed or unsealed block header.
     *
     * @generated from rpc flow.access.AccessAPI.GetLatestBlockHeader
     */
    getLatestBlockHeader: {
      name: "GetLatestBlockHeader",
      I: GetLatestBlockHeaderRequest,
      O: BlockHeaderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBlockHeaderByID gets a block header by ID.
     *
     * @generated from rpc flow.access.AccessAPI.GetBlockHeaderByID
     */
    getBlockHeaderByID: {
      name: "GetBlockHeaderByID",
      I: GetBlockHeaderByIDRequest,
      O: BlockHeaderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBlockHeaderByHeight gets a block header by height.
     *
     * @generated from rpc flow.access.AccessAPI.GetBlockHeaderByHeight
     */
    getBlockHeaderByHeight: {
      name: "GetBlockHeaderByHeight",
      I: GetBlockHeaderByHeightRequest,
      O: BlockHeaderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLatestBlock gets the full payload of the latest sealed or unsealed
     * block.
     *
     * @generated from rpc flow.access.AccessAPI.GetLatestBlock
     */
    getLatestBlock: {
      name: "GetLatestBlock",
      I: GetLatestBlockRequest,
      O: BlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBlockByID gets a full block by ID.
     *
     * @generated from rpc flow.access.AccessAPI.GetBlockByID
     */
    getBlockByID: {
      name: "GetBlockByID",
      I: GetBlockByIDRequest,
      O: BlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetBlockByHeight gets a full block by height.
     *
     * @generated from rpc flow.access.AccessAPI.GetBlockByHeight
     */
    getBlockByHeight: {
      name: "GetBlockByHeight",
      I: GetBlockByHeightRequest,
      O: BlockResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetCollectionByID gets a collection by ID.
     *
     * @generated from rpc flow.access.AccessAPI.GetCollectionByID
     */
    getCollectionByID: {
      name: "GetCollectionByID",
      I: GetCollectionByIDRequest,
      O: CollectionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * SendTransaction submits a transaction to the network.
     *
     * @generated from rpc flow.access.AccessAPI.SendTransaction
     */
    sendTransaction: {
      name: "SendTransaction",
      I: SendTransactionRequest,
      O: SendTransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTransaction gets a transaction by ID.
     *
     * @generated from rpc flow.access.AccessAPI.GetTransaction
     */
    getTransaction: {
      name: "GetTransaction",
      I: GetTransactionRequest,
      O: TransactionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTransactionResult gets the result of a transaction.
     *
     * @generated from rpc flow.access.AccessAPI.GetTransactionResult
     */
    getTransactionResult: {
      name: "GetTransactionResult",
      I: GetTransactionRequest,
      O: TransactionResultResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTransactionResultByIndex gets the result of a transaction at a specified
     * block and index
     *
     * @generated from rpc flow.access.AccessAPI.GetTransactionResultByIndex
     */
    getTransactionResultByIndex: {
      name: "GetTransactionResultByIndex",
      I: GetTransactionByIndexRequest,
      O: TransactionResultResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTransactionResultsByBlockID gets all the transaction results for a
     * specified block
     *
     * @generated from rpc flow.access.AccessAPI.GetTransactionResultsByBlockID
     */
    getTransactionResultsByBlockID: {
      name: "GetTransactionResultsByBlockID",
      I: GetTransactionsByBlockIDRequest,
      O: TransactionResultsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTransactionsByBlockID gets all the transactions for a specified block
     *
     * @generated from rpc flow.access.AccessAPI.GetTransactionsByBlockID
     */
    getTransactionsByBlockID: {
      name: "GetTransactionsByBlockID",
      I: GetTransactionsByBlockIDRequest,
      O: TransactionsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAccount is an alias for GetAccountAtLatestBlock.
     *
     * Warning: this function is deprecated. It behaves identically to
     * GetAccountAtLatestBlock and will be removed in a future version.
     *
     * @generated from rpc flow.access.AccessAPI.GetAccount
     */
    getAccount: {
      name: "GetAccount",
      I: GetAccountRequest,
      O: GetAccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAccountAtLatestBlock gets an account by address from the latest sealed
     * execution state.
     *
     * @generated from rpc flow.access.AccessAPI.GetAccountAtLatestBlock
     */
    getAccountAtLatestBlock: {
      name: "GetAccountAtLatestBlock",
      I: GetAccountAtLatestBlockRequest,
      O: AccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetAccountAtBlockHeight gets an account by address at the given block
     * height
     *
     * @generated from rpc flow.access.AccessAPI.GetAccountAtBlockHeight
     */
    getAccountAtBlockHeight: {
      name: "GetAccountAtBlockHeight",
      I: GetAccountAtBlockHeightRequest,
      O: AccountResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ExecuteScriptAtLatestBlock executes a read-only Cadence script against the
     * latest sealed execution state.
     *
     * @generated from rpc flow.access.AccessAPI.ExecuteScriptAtLatestBlock
     */
    executeScriptAtLatestBlock: {
      name: "ExecuteScriptAtLatestBlock",
      I: ExecuteScriptAtLatestBlockRequest,
      O: ExecuteScriptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ExecuteScriptAtBlockID executes a ready-only Cadence script against the
     * execution state at the block with the given ID.
     *
     * @generated from rpc flow.access.AccessAPI.ExecuteScriptAtBlockID
     */
    executeScriptAtBlockID: {
      name: "ExecuteScriptAtBlockID",
      I: ExecuteScriptAtBlockIDRequest,
      O: ExecuteScriptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * ExecuteScriptAtBlockHeight executes a ready-only Cadence script against the
     * execution state at the given block height.
     *
     * @generated from rpc flow.access.AccessAPI.ExecuteScriptAtBlockHeight
     */
    executeScriptAtBlockHeight: {
      name: "ExecuteScriptAtBlockHeight",
      I: ExecuteScriptAtBlockHeightRequest,
      O: ExecuteScriptResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetEventsForHeightRange retrieves events emitted within the specified block
     * range.
     *
     * @generated from rpc flow.access.AccessAPI.GetEventsForHeightRange
     */
    getEventsForHeightRange: {
      name: "GetEventsForHeightRange",
      I: GetEventsForHeightRangeRequest,
      O: EventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetEventsForBlockIDs retrieves events for the specified block IDs and event
     * type.
     *
     * @generated from rpc flow.access.AccessAPI.GetEventsForBlockIDs
     */
    getEventsForBlockIDs: {
      name: "GetEventsForBlockIDs",
      I: GetEventsForBlockIDsRequest,
      O: EventsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetNetworkParameters retrieves the Flow network details
     *
     * @generated from rpc flow.access.AccessAPI.GetNetworkParameters
     */
    getNetworkParameters: {
      name: "GetNetworkParameters",
      I: GetNetworkParametersRequest,
      O: GetNetworkParametersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetLatestProtocolStateSnapshot retrieves the latest sealed protocol state
     * snapshot. Used by Flow nodes joining the network to bootstrap a
     * space-efficient local state.
     *
     * @generated from rpc flow.access.AccessAPI.GetLatestProtocolStateSnapshot
     */
    getLatestProtocolStateSnapshot: {
      name: "GetLatestProtocolStateSnapshot",
      I: GetLatestProtocolStateSnapshotRequest,
      O: ProtocolStateSnapshotResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetExecutionResultForBlockID returns Execution Result for a given block.
     * At present, Access Node might not have execution results for every block
     * and as usual, until sealed, this data can change
     *
     * @generated from rpc flow.access.AccessAPI.GetExecutionResultForBlockID
     */
    getExecutionResultForBlockID: {
      name: "GetExecutionResultForBlockID",
      I: GetExecutionResultForBlockIDRequest,
      O: ExecutionResultForBlockIDResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

