// @generated by protoc-gen-connect-web v0.3.2 with parameter "target=ts"
// @generated from file flow/executiondata/executiondata.proto (package flow.access, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetExecutionDataByBlockIDRequest, GetExecutionDataByBlockIDResponse } from "./executiondata_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * ExecutionDataAPI is the API for providing Execution state sync data, currently from Access Nodes
 *
 * ExecutionState
 * GetExecutionDataByBlockID returns the execution_data object. Currently for
 * use by the archive node to update its execution state.
 *
 * @generated from service flow.access.ExecutionDataAPI
 */
export const ExecutionDataAPI = {
  typeName: "flow.access.ExecutionDataAPI",
  methods: {
    /**
     * @generated from rpc flow.access.ExecutionDataAPI.GetExecutionDataByBlockID
     */
    getExecutionDataByBlockID: {
      name: "GetExecutionDataByBlockID",
      I: GetExecutionDataByBlockIDRequest,
      O: GetExecutionDataByBlockIDResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

